[build]
  command = "yarn install && yarn run build"
  publish = "public/"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "true"
  PYTHON_VERSION = "3.9"
  GO_VERSION = "1.19"

[build.processing.html]
  pretty_urls = true

[template]
  incoming-hooks = ["Webflow"]

[template.environment]
  WEBFLOW_URL = ""

# [[plugins]]
# package = "netlify-plugin-subfont"
