[build]
  command = "yarn build"
  publish = "public/"

[build.environment]
  NETLIFY_USE_YARN = "true"
  GO_VERSION = "1.19"

[build.processing.html]
  pretty_urls = true

[template]
  incoming-hooks = ["Webflow"]

[template.environment]
  WEBFLOW_URL = ""

# [[plugins]]
# package = "netlify-plugin-subfont"
